version: '3'

services:
  mongodb:
    container_name: mongodbs
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mynet

  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 3000
      BASE_URL: "/api/clothes"
      MONGO_LOCAL_URI: mongodb://mongodbs:27017/clothe-backend
    ports:
      - "3000:3000"
    networks:
      - mynet
    depends_on:
      - mongodb
volumes:
  mongodb-data:


networks:
  mynet:
    driver: bridge
